ffmpeg -i door.mp3 door.aac
ffmpeg -i dragon.mp3 dragon.aac
ffmpeg -i evillaugh.mp3 evillaugh.aac
ffmpeg -i ghost1.mp3 ghost1.aac
ffmpeg -i ghost2.mp3 ghost2.aac
ffmpeg -i ghost3.mp3 ghost3.aac
ffmpeg -i monster.mp3 monster.aac
ffmpeg -i owl1.mp3 owl1.aac
ffmpeg -i owl2.mp3 owl2.aac
ffmpeg -i rain.mp3 rain.aac
ffmpeg -i scream.mp3 scream.aac
ffmpeg -i storm.mp3 storm.aac
ffmpeg -i witchlaugh.mp3 witchlaugh.aac
